### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by blaiz** [heavymery/grunt-require-rev#2]
Hi,

I can't get this plug-in to work. I've tried a few different configurations and this plug-in always crashes. I tried this:
```js
    requireRev: {
      develop: {
        expand: true,
        cwd: 'build/develop',
        src: [
          'features/foobar.js',
          'features/foobar-controller.js'
        ]
      }
    }
```
where foobar requires foobar-controller as a dependency. I've gotten 2 different error messages depending on the configuration. This one:
```
Running "requireRev:expand" (requireRev) task
Warning: Object true has no method 'indexOf' Use --force to continue.
```
And this one:
```
Warning: Cannot read property 'source' of undefined Use --force to continue.
TypeError: Cannot read property 'source' of undefined
    at Object.<anonymous> (/foo/node_modules/grunt-require-rev/tasks/requireRev.js:323:87)
    at Object.<anonymous> (/foo/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/foo/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/foo/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/foo/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/foo/node_modules/grunt/lib/util/task.js:300:12)
    at /foo/node_modules/grunt/lib/util/task.js:227:11
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

Have you seen that before? do you know how to resolve it?

**Comment by MichaelKubovic** [comment]
Hey there, have you ever solved this problem?

**Comment by heavymery** [comment]
Hey guys,  sorry for late response :)

What version of node.js are you using?
And could you show me sample code of `features/foobar.js` and `features/foobar-controller.js`?

**Comment by blaiz** [comment]
Wow, that was a year ago. I don't remember what project this happened on. I don't think I ever resolved this issue. If no one can reproduce it, feel free to close this issue.
